# Generated by Django 5.2.5 on 2025-08-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_heading_post_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postanalytics',
            old_name='clik_through_rate',
            new_name='click_through_rate',
        ),
        migrations.RenameField(
            model_name='postanalytics',
            old_name='cliks',
            new_name='clicks',
        ),
    ]
